### ISSUE TITLE
Unable to Find Stream package

### ISSUE THREAD

**Issue by danlugo92** [shocknet/wallet#135]
![image](https://user-images.githubusercontent.com/32064271/84401041-ca12d300-abd0-11ea-99bd-87aa80fc26c8.png)

Happens only in one env (ubuntu 20.04, watchman compiled without python support).

Fixed by rebooting, clearing caches and rerunning compilation steps.

**Comment by boufni95** [comment]
I have seen an error like this while running the wallet right after I change from a branch to another, removing node_modules and doing a yarn install solves it to me
