### ISSUE TITLE
Implement keyboard awareness in views

### ISSUE THREAD

**Issue by danlugo92** [shocknet/wallet#29]
Tried with a couple of libraries to no sucess. Must be revisited.

**Comment by capitalistdog** [comment]
Added @Emad-salah to give it a 2nd look.

**Comment by danlugo92** [comment]
@Emad-salah Implemented a custom solution in one of the components he made. Maybe we can port that to `<OnboardingScreen />` and other container-like components.

**Comment by danlugo92** [comment]
The chat  screen also suffers due to this react native bug.

Possible solution:

https://github.com/facebook/react-native/issues/6785#issuecomment-263607868
